// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class Position_Response;
@class Position_Response_Builder;

@interface PositionResponseRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Position_Response : PBGeneratedMessage {
@private
  BOOL hasState_:1;
  BOOL hasErrMessage_:1;
  BOOL state_:1;
  NSString* errMessage;
}
- (BOOL) hasState;
- (BOOL) hasErrMessage;
- (BOOL) state;
@property (readonly, retain) NSString* errMessage;

+ (Position_Response*) defaultInstance;
- (Position_Response*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Position_Response_Builder*) builder;
+ (Position_Response_Builder*) builder;
+ (Position_Response_Builder*) builderWithPrototype:(Position_Response*) prototype;

+ (Position_Response*) parseFromData:(NSData*) data;
+ (Position_Response*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Position_Response*) parseFromInputStream:(NSInputStream*) input;
+ (Position_Response*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Position_Response*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Position_Response*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Position_Response_Builder : PBGeneratedMessage_Builder {
@private
  Position_Response* result;
}

- (Position_Response*) defaultInstance;

- (Position_Response_Builder*) clear;
- (Position_Response_Builder*) clone;

- (Position_Response*) build;
- (Position_Response*) buildPartial;

- (Position_Response_Builder*) mergeFrom:(Position_Response*) other;
- (Position_Response_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Position_Response_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasState;
- (BOOL) state;
- (Position_Response_Builder*) setState:(BOOL) value;
- (Position_Response_Builder*) clearState;

- (BOOL) hasErrMessage;
- (NSString*) errMessage;
- (Position_Response_Builder*) setErrMessage:(NSString*) value;
- (Position_Response_Builder*) clearErrMessage;
@end

