// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "PositionResponse.pb.h"

@implementation PositionResponseRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [PositionResponseRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface Position_Response ()
@property BOOL state;
@property (retain) NSString* errMessage;
@end

@implementation Position_Response

- (BOOL) hasState {
  return !!hasState_;
}
- (void) setHasState:(BOOL) value {
  hasState_ = !!value;
}
- (BOOL) state {
  return !!state_;
}
- (void) setState:(BOOL) value {
  state_ = !!value;
}
- (BOOL) hasErrMessage {
  return !!hasErrMessage_;
}
- (void) setHasErrMessage:(BOOL) value {
  hasErrMessage_ = !!value;
}
@synthesize errMessage;
- (void) dealloc {
  self.errMessage = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.state = NO;
    self.errMessage = @"";
  }
  return self;
}
static Position_Response* defaultPosition_ResponseInstance = nil;
+ (void) initialize {
  if (self == [Position_Response class]) {
    defaultPosition_ResponseInstance = [[Position_Response alloc] init];
  }
}
+ (Position_Response*) defaultInstance {
  return defaultPosition_ResponseInstance;
}
- (Position_Response*) defaultInstance {
  return defaultPosition_ResponseInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasState) {
    [output writeBool:1 value:self.state];
  }
  if (self.hasErrMessage) {
    [output writeString:2 value:self.errMessage];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasState) {
    size += computeBoolSize(1, self.state);
  }
  if (self.hasErrMessage) {
    size += computeStringSize(2, self.errMessage);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (Position_Response*) parseFromData:(NSData*) data {
  return (Position_Response*)[[[Position_Response builder] mergeFromData:data] build];
}
+ (Position_Response*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Position_Response*)[[[Position_Response builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Position_Response*) parseFromInputStream:(NSInputStream*) input {
  return (Position_Response*)[[[Position_Response builder] mergeFromInputStream:input] build];
}
+ (Position_Response*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Position_Response*)[[[Position_Response builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Position_Response*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Position_Response*)[[[Position_Response builder] mergeFromCodedInputStream:input] build];
}
+ (Position_Response*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Position_Response*)[[[Position_Response builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Position_Response_Builder*) builder {
  return [[[Position_Response_Builder alloc] init] autorelease];
}
+ (Position_Response_Builder*) builderWithPrototype:(Position_Response*) prototype {
  return [[Position_Response builder] mergeFrom:prototype];
}
- (Position_Response_Builder*) builder {
  return [Position_Response builder];
}
@end

@interface Position_Response_Builder()
@property (retain) Position_Response* result;
@end

@implementation Position_Response_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[Position_Response alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (Position_Response_Builder*) clear {
  self.result = [[[Position_Response alloc] init] autorelease];
  return self;
}
- (Position_Response_Builder*) clone {
  return [Position_Response builderWithPrototype:result];
}
- (Position_Response*) defaultInstance {
  return [Position_Response defaultInstance];
}
- (Position_Response*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Position_Response*) buildPartial {
  Position_Response* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (Position_Response_Builder*) mergeFrom:(Position_Response*) other {
  if (other == [Position_Response defaultInstance]) {
    return self;
  }
  if (other.hasState) {
    [self setState:other.state];
  }
  if (other.hasErrMessage) {
    [self setErrMessage:other.errMessage];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (Position_Response_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (Position_Response_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setState:[input readBool]];
        break;
      }
      case 18: {
        [self setErrMessage:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasState {
  return result.hasState;
}
- (BOOL) state {
  return result.state;
}
- (Position_Response_Builder*) setState:(BOOL) value {
  result.hasState = YES;
  result.state = value;
  return self;
}
- (Position_Response_Builder*) clearState {
  result.hasState = NO;
  result.state = NO;
  return self;
}
- (BOOL) hasErrMessage {
  return result.hasErrMessage;
}
- (NSString*) errMessage {
  return result.errMessage;
}
- (Position_Response_Builder*) setErrMessage:(NSString*) value {
  result.hasErrMessage = YES;
  result.errMessage = value;
  return self;
}
- (Position_Response_Builder*) clearErrMessage {
  result.hasErrMessage = NO;
  result.errMessage = @"";
  return self;
}
@end

