// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class Position_Request;
@class Position_Request_Builder;
@class Positions;
@class Positions_Builder;

@interface PositionRequestRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Position_Request : PBGeneratedMessage {
@private
  BOOL hasUindex_:1;
  NSString* uindex;
  NSMutableArray* mutableUpPositionsList;
}
- (BOOL) hasUindex;
@property (readonly, retain) NSString* uindex;
- (NSArray*) upPositionsList;
- (Positions*) upPositionsAtIndex:(int32_t) index;

+ (Position_Request*) defaultInstance;
- (Position_Request*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Position_Request_Builder*) builder;
+ (Position_Request_Builder*) builder;
+ (Position_Request_Builder*) builderWithPrototype:(Position_Request*) prototype;

+ (Position_Request*) parseFromData:(NSData*) data;
+ (Position_Request*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Position_Request*) parseFromInputStream:(NSInputStream*) input;
+ (Position_Request*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Position_Request*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Position_Request*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Position_Request_Builder : PBGeneratedMessage_Builder {
@private
  Position_Request* result;
}

- (Position_Request*) defaultInstance;

- (Position_Request_Builder*) clear;
- (Position_Request_Builder*) clone;

- (Position_Request*) build;
- (Position_Request*) buildPartial;

- (Position_Request_Builder*) mergeFrom:(Position_Request*) other;
- (Position_Request_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Position_Request_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) upPositionsList;
- (Positions*) upPositionsAtIndex:(int32_t) index;
- (Position_Request_Builder*) replaceUpPositionsAtIndex:(int32_t) index with:(Positions*) value;
- (Position_Request_Builder*) addUpPositions:(Positions*) value;
- (Position_Request_Builder*) addAllUpPositions:(NSArray*) values;
- (Position_Request_Builder*) clearUpPositionsList;

- (BOOL) hasUindex;
- (NSString*) uindex;
- (Position_Request_Builder*) setUindex:(NSString*) value;
- (Position_Request_Builder*) clearUindex;
@end

@interface Positions : PBGeneratedMessage {
@private
  BOOL hasX_:1;
  BOOL hasY_:1;
  BOOL hasH_:1;
  BOOL hasPower_:1;
  BOOL hasPtype_:1;
  BOOL hasCreateTime_:1;
  Float64 x;
  Float64 y;
  Float64 h;
  Float64 power;
  int32_t ptype;
  NSString* createTime;
}
- (BOOL) hasX;
- (BOOL) hasY;
- (BOOL) hasH;
- (BOOL) hasPtype;
- (BOOL) hasPower;
- (BOOL) hasCreateTime;
@property (readonly) Float64 x;
@property (readonly) Float64 y;
@property (readonly) Float64 h;
@property (readonly) int32_t ptype;
@property (readonly) Float64 power;
@property (readonly, retain) NSString* createTime;

+ (Positions*) defaultInstance;
- (Positions*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Positions_Builder*) builder;
+ (Positions_Builder*) builder;
+ (Positions_Builder*) builderWithPrototype:(Positions*) prototype;

+ (Positions*) parseFromData:(NSData*) data;
+ (Positions*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Positions*) parseFromInputStream:(NSInputStream*) input;
+ (Positions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Positions*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Positions*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Positions_Builder : PBGeneratedMessage_Builder {
@private
  Positions* result;
}

- (Positions*) defaultInstance;

- (Positions_Builder*) clear;
- (Positions_Builder*) clone;

- (Positions*) build;
- (Positions*) buildPartial;

- (Positions_Builder*) mergeFrom:(Positions*) other;
- (Positions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Positions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasX;
- (Float64) x;
- (Positions_Builder*) setX:(Float64) value;
- (Positions_Builder*) clearX;

- (BOOL) hasY;
- (Float64) y;
- (Positions_Builder*) setY:(Float64) value;
- (Positions_Builder*) clearY;

- (BOOL) hasH;
- (Float64) h;
- (Positions_Builder*) setH:(Float64) value;
- (Positions_Builder*) clearH;

- (BOOL) hasPtype;
- (int32_t) ptype;
- (Positions_Builder*) setPtype:(int32_t) value;
- (Positions_Builder*) clearPtype;

- (BOOL) hasPower;
- (Float64) power;
- (Positions_Builder*) setPower:(Float64) value;
- (Positions_Builder*) clearPower;

- (BOOL) hasCreateTime;
- (NSString*) createTime;
- (Positions_Builder*) setCreateTime:(NSString*) value;
- (Positions_Builder*) clearCreateTime;
@end

