// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "TestResponse.pb.h"

@implementation TestResponseRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [TestResponseRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface TestResponse ()
@property BOOL issuccess;
@end

@implementation TestResponse

- (BOOL) hasIssuccess {
  return !!hasIssuccess_;
}
- (void) setHasIssuccess:(BOOL) value {
  hasIssuccess_ = !!value;
}
- (BOOL) issuccess {
  return !!issuccess_;
}
- (void) setIssuccess:(BOOL) value {
  issuccess_ = !!value;
}
- (void) dealloc {
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.issuccess = NO;
  }
  return self;
}
static TestResponse* defaultTestResponseInstance = nil;
+ (void) initialize {
  if (self == [TestResponse class]) {
    defaultTestResponseInstance = [[TestResponse alloc] init];
  }
}
+ (TestResponse*) defaultInstance {
  return defaultTestResponseInstance;
}
- (TestResponse*) defaultInstance {
  return defaultTestResponseInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasIssuccess) {
    [output writeBool:1 value:self.issuccess];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasIssuccess) {
    size += computeBoolSize(1, self.issuccess);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (TestResponse*) parseFromData:(NSData*) data {
  return (TestResponse*)[[[TestResponse builder] mergeFromData:data] build];
}
+ (TestResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (TestResponse*)[[[TestResponse builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (TestResponse*) parseFromInputStream:(NSInputStream*) input {
  return (TestResponse*)[[[TestResponse builder] mergeFromInputStream:input] build];
}
+ (TestResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (TestResponse*)[[[TestResponse builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (TestResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (TestResponse*)[[[TestResponse builder] mergeFromCodedInputStream:input] build];
}
+ (TestResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (TestResponse*)[[[TestResponse builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (TestResponse_Builder*) builder {
  return [[[TestResponse_Builder alloc] init] autorelease];
}
+ (TestResponse_Builder*) builderWithPrototype:(TestResponse*) prototype {
  return [[TestResponse builder] mergeFrom:prototype];
}
- (TestResponse_Builder*) builder {
  return [TestResponse builder];
}
@end

@interface TestResponse_Builder()
@property (retain) TestResponse* result;
@end

@implementation TestResponse_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[TestResponse alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (TestResponse_Builder*) clear {
  self.result = [[[TestResponse alloc] init] autorelease];
  return self;
}
- (TestResponse_Builder*) clone {
  return [TestResponse builderWithPrototype:result];
}
- (TestResponse*) defaultInstance {
  return [TestResponse defaultInstance];
}
- (TestResponse*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (TestResponse*) buildPartial {
  TestResponse* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (TestResponse_Builder*) mergeFrom:(TestResponse*) other {
  if (other == [TestResponse defaultInstance]) {
    return self;
  }
  if (other.hasIssuccess) {
    [self setIssuccess:other.issuccess];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (TestResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (TestResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setIssuccess:[input readBool]];
        break;
      }
    }
  }
}
- (BOOL) hasIssuccess {
  return result.hasIssuccess;
}
- (BOOL) issuccess {
  return result.issuccess;
}
- (TestResponse_Builder*) setIssuccess:(BOOL) value {
  result.hasIssuccess = YES;
  result.issuccess = value;
  return self;
}
- (TestResponse_Builder*) clearIssuccess {
  result.hasIssuccess = NO;
  result.issuccess = NO;
  return self;
}
@end

