// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class TestResponse;
@class TestResponse_Builder;

@interface TestResponseRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface TestResponse : PBGeneratedMessage {
@private
  BOOL hasIssuccess_:1;
  BOOL issuccess_:1;
}
- (BOOL) hasIssuccess;
- (BOOL) issuccess;

+ (TestResponse*) defaultInstance;
- (TestResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TestResponse_Builder*) builder;
+ (TestResponse_Builder*) builder;
+ (TestResponse_Builder*) builderWithPrototype:(TestResponse*) prototype;

+ (TestResponse*) parseFromData:(NSData*) data;
+ (TestResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestResponse*) parseFromInputStream:(NSInputStream*) input;
+ (TestResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TestResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TestResponse_Builder : PBGeneratedMessage_Builder {
@private
  TestResponse* result;
}

- (TestResponse*) defaultInstance;

- (TestResponse_Builder*) clear;
- (TestResponse_Builder*) clone;

- (TestResponse*) build;
- (TestResponse*) buildPartial;

- (TestResponse_Builder*) mergeFrom:(TestResponse*) other;
- (TestResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TestResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIssuccess;
- (BOOL) issuccess;
- (TestResponse_Builder*) setIssuccess:(BOOL) value;
- (TestResponse_Builder*) clearIssuccess;
@end

