// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class MoTestInfo;
@class MoTestInfo_Builder;
@class TestRequest;
@class TestRequest_Builder;

@interface TestRequestRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface MoTestInfo : PBGeneratedMessage {
@private
  BOOL hasIosVersion_:1;
  BOOL hasIphoneVewsion_:1;
  BOOL hasLongitude_:1;
  BOOL hasLatitude_:1;
  BOOL hasDate_:1;
  NSString* iosVersion;
  NSString* iphoneVewsion;
  NSString* longitude;
  NSString* latitude;
  NSString* date;
}
- (BOOL) hasIosVersion;
- (BOOL) hasIphoneVewsion;
- (BOOL) hasLongitude;
- (BOOL) hasLatitude;
- (BOOL) hasDate;
@property (readonly, retain) NSString* iosVersion;
@property (readonly, retain) NSString* iphoneVewsion;
@property (readonly, retain) NSString* longitude;
@property (readonly, retain) NSString* latitude;
@property (readonly, retain) NSString* date;

+ (MoTestInfo*) defaultInstance;
- (MoTestInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MoTestInfo_Builder*) builder;
+ (MoTestInfo_Builder*) builder;
+ (MoTestInfo_Builder*) builderWithPrototype:(MoTestInfo*) prototype;

+ (MoTestInfo*) parseFromData:(NSData*) data;
+ (MoTestInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MoTestInfo*) parseFromInputStream:(NSInputStream*) input;
+ (MoTestInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MoTestInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MoTestInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MoTestInfo_Builder : PBGeneratedMessage_Builder {
@private
  MoTestInfo* result;
}

- (MoTestInfo*) defaultInstance;

- (MoTestInfo_Builder*) clear;
- (MoTestInfo_Builder*) clone;

- (MoTestInfo*) build;
- (MoTestInfo*) buildPartial;

- (MoTestInfo_Builder*) mergeFrom:(MoTestInfo*) other;
- (MoTestInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MoTestInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIosVersion;
- (NSString*) iosVersion;
- (MoTestInfo_Builder*) setIosVersion:(NSString*) value;
- (MoTestInfo_Builder*) clearIosVersion;

- (BOOL) hasIphoneVewsion;
- (NSString*) iphoneVewsion;
- (MoTestInfo_Builder*) setIphoneVewsion:(NSString*) value;
- (MoTestInfo_Builder*) clearIphoneVewsion;

- (BOOL) hasLongitude;
- (NSString*) longitude;
- (MoTestInfo_Builder*) setLongitude:(NSString*) value;
- (MoTestInfo_Builder*) clearLongitude;

- (BOOL) hasLatitude;
- (NSString*) latitude;
- (MoTestInfo_Builder*) setLatitude:(NSString*) value;
- (MoTestInfo_Builder*) clearLatitude;

- (BOOL) hasDate;
- (NSString*) date;
- (MoTestInfo_Builder*) setDate:(NSString*) value;
- (MoTestInfo_Builder*) clearDate;
@end

@interface TestRequest : PBGeneratedMessage {
@private
  BOOL hasUsername_:1;
  NSString* username;
  NSMutableArray* mutableListMoTestInfoList;
}
- (BOOL) hasUsername;
@property (readonly, retain) NSString* username;
- (NSArray*) listMoTestInfoList;
- (MoTestInfo*) listMoTestInfoAtIndex:(int32_t) index;

+ (TestRequest*) defaultInstance;
- (TestRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TestRequest_Builder*) builder;
+ (TestRequest_Builder*) builder;
+ (TestRequest_Builder*) builderWithPrototype:(TestRequest*) prototype;

+ (TestRequest*) parseFromData:(NSData*) data;
+ (TestRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestRequest*) parseFromInputStream:(NSInputStream*) input;
+ (TestRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TestRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TestRequest_Builder : PBGeneratedMessage_Builder {
@private
  TestRequest* result;
}

- (TestRequest*) defaultInstance;

- (TestRequest_Builder*) clear;
- (TestRequest_Builder*) clone;

- (TestRequest*) build;
- (TestRequest*) buildPartial;

- (TestRequest_Builder*) mergeFrom:(TestRequest*) other;
- (TestRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TestRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) listMoTestInfoList;
- (MoTestInfo*) listMoTestInfoAtIndex:(int32_t) index;
- (TestRequest_Builder*) replaceListMoTestInfoAtIndex:(int32_t) index with:(MoTestInfo*) value;
- (TestRequest_Builder*) addListMoTestInfo:(MoTestInfo*) value;
- (TestRequest_Builder*) addAllListMoTestInfo:(NSArray*) values;
- (TestRequest_Builder*) clearListMoTestInfoList;

- (BOOL) hasUsername;
- (NSString*) username;
- (TestRequest_Builder*) setUsername:(NSString*) value;
- (TestRequest_Builder*) clearUsername;
@end

